"""Adds Goal model and creates a one to many relationship between the Goal and Task models. Adds goal_routes.py and associated testing file. Refactors creating models and filtering models to model_utilities.py.

Revision ID: 473292c27d74
Revises: d50b931bf109
Create Date: 2025-11-05 21:11:23.643256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473292c27d74'
down_revision = 'd50b931bf109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'goal', ['goal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
